### ISSUE TITLE
pentecôte

### ISSUE THREAD

**Issue by Pouet78** [AntoineAugusti/jours-feries-france#3]
Le Lundi de pentecôte n'était plus chômé de 2004 à 2008. De plus, c'est bien le Lundi de pentecôte, tout comme le Lundi de Pâques qui est férié. Pentecôte et Pâques sont des dimanches.

**Comment by AntoineAugusti** [comment]
> Le Lundi de pentecôte n'était plus chômé de 2004 à 2008.
C'était une question ouverte aux débats et la mesure a été partiellement appliquée... Je pense laisser comme ceci.

Pour le Lundi de Pâques et le de la Pentecôte, les jours fériés renseignés ici sont des lundis.

**Comment by Pouet78** [comment]
> Pour le Lundi de Pâques et le de la Pentecôte, les jours fériés renseignés ici sont des lundis.
Ma remarque est à propos du nom dans le code : "Pentecôte" contrairement au "**Lundi** de Pâques"
